config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks"}
  
  # For all non-Devise user pages
  resources :users
  resources :interests


  post '/users/:id/edit' => 'users#update_interest'

  post '/get_meetup_info' => 'pages#get_meetup_info'
  # Method for the user to select a location
  get '/select_location' => 'pages#select_location'
  # Saves user's interests using AJAX from the edit_user page
  post '/save_interest' => 'interests#save_interest'
  # Click on the X in the menu to remove a chat
  delete '/remove_chat/:id' => 'chats#destroy', as: 'remove_chat'

  resources :chats do
    resources :messages
  end

  # Direct the user to the chat room
  get '/events/:id' => 'events#show'
  resources :events
  # Clicking on main menu icon refreshes the menu contents
  get '/event_update' => 'chats#event_update'
  # Enought chatting for one day
  post '/unsubscribe/:id' => 'chats#leavechat'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable, 
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :interests, through: :interests_users

  # used for chats
  belongs_to :event
  has_many :chat_users
  has_many :chats, through: :chat_users
  has_many :messages
  validates :name, :presence => true
  
  def distance a, b
	  rad_per_deg = Math::PI/180  # PI / 180
	  rkm = 6371                  # Earth radius in kilometers
	  rm = rkm * 1000             # Radius in meters

	  dlon_rad = (b[1]-a[1]) * rad_per_deg  # Delta, converted to rad
	  dlat_rad = (b[0]-a[0]) * rad_per_deg

	  lat1_rad, lon1_rad = a.map! {|i| i * rad_per_deg }
	  lat2_rad, lon2_rad = b.map! {|i| i * rad_per_deg }

	  a = Math.sin(dlat_rad/2)**2 + Math.cos(lat1_rad) * Math.cos(lat2_rad) * Math.sin(dlon_rad/2)**2
	  c = 2 * Math::atan2(Math::sqrt(a), Math::sqrt(1-a))

	  meters = rm * c # Delta in meters
	  miles = meters * 0.000621371
	  # get exact difference instead above
    # miles.round(1)
	end


  def self.from_omniauth(auth)

    # gets and sets auth token for user
    where(provider: auth.provider, uid: auth.uid.to_s).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid.to_s
        user.auth_token = auth.credentials.token
        user.refresh_token = auth.credentials.refresh_token
        user.expires_at = auth.credentials.expires_at
        user.name = auth.info.name
        user.private_messages = true

      if auth.info.photo_url != nil
        user.photo = auth.info.photo_url

        # user.location = auth.extra.raw_info.city
      end  

    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  def show_user user
    params = {member_id: user.uid}
    meetup_api = MeetupApi.new
    return meetup_api.members(params)
  end

  def get_user_event_list user

    # control number of events in select_location dropdown
    options = { 
        member_id: user.uid,
        time: "-2d,2d"
    }
    meetup_api = MeetupApi.new
    return meetup_api.events(options)
    binding.pry
  end 

  def get_user_events_today events
    i = 0
    events_today = []
    if events["results"] != nil
      while i < events["results"].length 
        if Time.at(events["results"][i]["time"] / 1000) - Time.now < 1200.hours
          
          events_today << {
          :name => events["results"][i]["name"],
          :id => events["results"][i]["id"],
          :time => Time.at(events["results"][i]["time"] / 1000),
          :group => events["results"][i]["group"]["name"]
          }
        end
        i += 1
      end
    end
    return events_today 
  end

  def get_user_event_details event_id
    params = {event_id: event_id,
              member_id: uid}
    meetup_api = MeetupApi.new

    return meetup_api.events(params)
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_action :get_user, only: [:show, :edit, :update, :save_interest, :update_interest]

  def get_user
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
    @user = current_user
  end

  def show
    # gets user entered in params
    @member = @user.show_user(@user)
    @interests = @user.interests

    # all the chats that are active
    chats = @user.event.chats

    # add hashtag to match with chats and add interest if a chat exists for it
    @interests_with_chats = {}
    @interests.each do |interest|
      @interests_with_chats[interest.name] = false
      chats.each do |chat| 
        if ("#"+interest.name) == chat.category
          @interests_with_chats[interest.name] = true
        end
      end
    end

  end

  def edit
    @interests = Interest.all
    @events = @user.get_user_event_list(@user)
    @events_today = @user.get_user_events_today(@events)
  end

  def update

    # remove past chat_users relation that belong to user
    current_user.chat_users.destroy_all

    # get event details of selected event
    @selected_events = @user.get_user_event_details(params['event_id'])['results'][0]['name']

    # find existing or create event with id from meetups api and selected event
    event = Event.find_or_create_by(meetup_event_id: params[:event_id], name: @selected_events)

    # make the main default chatroom for this event here
    chat = Chat.find_or_create_by(category: "main", event_id: event.id)
    ChatUser.find_or_create_by(chat_id: chat.id, user_id: current_user.id)
    
    # update user profile
    if @user.update_attributes(event_id: event.id, event_name: @selected_events)
      # send to edit profile page
      redirect_to edit_user_path(@user)
  	end
  end

  def update_interest    
    @user.update_attributes(:private_messages => params['update_interest']['private_messages'], :lat => params['update_interest']['lat'], :lon => params['update_interest']['lon'], :phone => params['update_interest']['phone'], :bio => params['update_interest']['bio']  )
    redirect_to event_path(@user.event_id)
  end

  def save_interest
    new_interest = Interest.find_or_create_by(:name => params[:interest])
    @user.interests << new_interest
    respond_to do |format|
    format.json { render json: new_interest }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<!-- If the event's location is private, skip this page and spit out a message -->
<% if @user.get_user_event_details(@user.event.meetup_event_id)['results'][0]['venue'] != nil %>

	<!-- As long as there are events in the queue, run this code -->
	<% if @events["results"] != nil && @events["results"].length > 0 %>
		<section id='profile-details'>
			<div id='photo-container'>
				<%= image_tag @user.photo, class: 'photo' %>
			</div>
			<div id='profile-info-container'>
				<h1 id='name'><%= @user.name %></h1>
				<p id='location'><%= @user.get_user_event_details(@user.event.meetup_event_id)['results'][0]['name'] %></p>
			</div>
		</section>

		<div class="container">
			<%= form_for :update_interest do |f| %>

				<section>
					<label>YOUR INTRO:</label>
					<%= f.text_area :bio, value: @user.bio, placeholder: '140 characters max', maxlength: 140, id: 'bio-field', class: 'expand' %>			
				</section>

			 	<section id='interests'>
			 		<label>YOUR INTERESTS:</label>
					<%= text_field_tag :interests, nil, placeholder: " Add up to five", id: 'interests-field', class: 'expand' %>	
					<div>

						<!-- Users can type in interests, then on click, they will disappear -->
						<ul class='interest-cloud' id='my-interests'>
							<% @user.interests.order("name ASC").each do |interest| %>
								<li class="interest"><%= link_to ('#' + interest.name), interest_path(interest), :class => 'remote-delete button green', :title => 'Delete ' + interest.name %></li>
							<% end %>
						</ul>
					</div>					
					<div class="switch">
						<%= f.check_box :private_messages?, checked: @user.private_messages, id: 'cmn-toggle-1', class: 'cmn-toggle cmn-toggle-round' %>
						<label for="cmn-toggle-1"></label>
						<p id='private-messages'>Allow SMS messages</p>
						<div id='phone'>
							<%= label_tag 'phone' %>
							<%= f.text_field :phone, value: @user.phone, maxlength: 12, placeholder: 'ex) 555-555-5555', class: 'expand center', id: 'phone-input' %>
						</div>
					</div>
					<%=f.hidden_field :lat, id: 'lat'%>
					<%=f.hidden_field :lon, id: 'lon'%>	
					<%= f.submit "Continue", id: "start-chat", class: "button expand" %>
					<p class="detecting-location">Detecting Location</p>
				</section>
			<% end %>	
		</div>
	<% else %>
		<div class="container">

			<!-- If the user has events today, this message is displayed -->
			<p class='apologies'>Sorry, no events for this user. Come back on the day of a Meetup.</p>
		</div>
	<% end %>
<% else %>
	<div class="container">
		
		<!-- This is displayed if the place of the event isn't public -->
		<p class='apologies'>Your place isn't public, yo! WTF?</p>
	</div>
<% end %>

app/views/users/show.html.erb
<%= render 'layouts/header' %>

<!-- This section is outside the container so it wraps edge-to-edge -->
	<section id='profile-details'>
		<div id='photo-container'>
			<%= image_tag @user.photo, class: 'photo' %>
		</div>
		<div id='profile-info-container'>
			<h1 id='name'><%= @user.name %></h1>
			<p id='location'><%= truncate(@user.get_user_event_details(@user.event.meetup_event_id)['results'][0]['name'], length: 28) %></p>
		</div>
	</section>

<div class="container">
 	<% if @user.bio != '' %>
	 	<section>
			<label>EVENT STATUS</label>
			<p id="bio"><%= @user.bio %></p>
		</section>
	<% end %>

	<section id='interests'>
		<label>INTERESTS</label>
		<ul class='interest-cloud'>
			<% @interests_with_chats.each do |interestname, present| %>
				 
				<% if present %> 
				<!-- Click to spawn a new room based on the user's interest -->
					<li class="interest start-chat active-chats" data-category= <%= '#' + interestname %> data-event_id=<%= @user.event_id.to_s %> id=<%=interestname%>>
						<a class="green button active-chats" href="#">
							#<%= interestname %> 
						</a>
					</li>
				<% else %>
					<li class="interest start-chat" data-category= <%= '#' + interestname %> data-event_id=<%= @user.event_id.to_s %> id=<%=interestname%>>
						<a class="green button" href="#">
							#<%= interestname %> 
						</a>
					</li>
				<% end %>				

			<% end %>
		</ul>
	</section>

</div>

<script>


	$(document).delegate(".start-chat", "click", function (e) {
		e.preventDefault();
        var category = $(this).data('category');  
        var event_id = $(this).data('event_id');

        // menu is finnicky with its labeling of data fields - set if unset
        if (event_id == null){
        	event_id = $(this).data('event-id');
        }
        $.post("/chats", { category: category, event_id: event_id}, function (data) {
        	// success
        	if(data.chat_name != "main"){
        		$(data.chat_name + "> a").css('background-color', '#407bfb');
        		$(data.chat_name).css('background-color', '#407bfb');
        	}
        }); 
    });	
</script>