config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks"}
  
  # For all non-Devise user pages
  resources :users
  resources :interests


  post '/users/:id/edit' => 'users#update_interest'

  post '/get_meetup_info' => 'pages#get_meetup_info'
  # Method for the user to select a location
  get '/select_location' => 'pages#select_location'
  # Saves user's interests using AJAX from the edit_user page
  post '/save_interest' => 'interests#save_interest'
  # Click on the X in the menu to remove a chat
  delete '/remove_chat/:id' => 'chats#destroy', as: 'remove_chat'

  resources :chats do
    resources :messages
  end

  # Direct the user to the chat room
  get '/events/:id' => 'events#show'
  resources :events
  # Clicking on main menu icon refreshes the menu contents
  get '/event_update' => 'chats#event_update'
  # Enought chatting for one day
  post '/unsubscribe/:id' => 'chats#leavechat'

end

app/models/chat.rb
class Chat < ActiveRecord::Base
  has_many :messages, dependent: :destroy
  belongs_to :event

  has_many :chat_users
  has_many :users, through: :chat_users

  def self.existing_chat(event_id, category)
    Chat.find_by(event_id: event_id, category: category)
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_filter :authenticate_user!
  layout false
  
  def create

    # look for chat based on event id from meetups create it if it doesn't exist
    
    # users can't have more than 5 chats
    if current_user.chats.count < 5 
      if Chat.existing_chat(params[:event_id],params[:category]).present?
        @chat = Chat.existing_chat(params[:event_id],params[:category])

        # if user never joined this chat add user to chat (ChatUser join table)
        if !@chat.users.include?(current_user)
          ChatUser.create(user_id: current_user.id, chat_id: @chat.id)
        end

      else
        
        # makes a chat with key values of sender and recipient ids
        @chat = Chat.create!(chat_params)

        # adds user to chat (ChatUser join table)
        ChatUser.create(user_id: current_user.id, chat_id: @chat.id)
      end
      # return this as data in ajax request, chat id, name, user (later two for heading)
      render json: { chat_id: @chat.id, chat_name: params[:category], user_count: @chat.users.count, event_name: @chat.event.name[0..15]}
    else

      # checks if chat is already existing, then render that chat if user already belongs to
      if Chat.existing_chat(params[:event_id],params[:category]).present?
        @chat = Chat.existing_chat(params[:event_id],params[:category])
        render json: { chat_id: @chat.id, chat_name: params[:category], user_count: @chat.users.count, event_name: @chat.event.name[0..15]}
      else

      # render main chat if user is maxed out on number of chats
        render json: { chat_id: current_user.chats.first.id, chat_name: "main", user_count: current_user.chats.first.users.count, event_name: current_user.event.name[0..15]}
      end
    end
  end
  
  def show

    # find chat and chat's messages and instantiate new message for form
    @chat = Chat.find(params[:id])
    @messages = @chat.messages
    @message = Message.new
  end

  def leavechat
    @chat = Chat.find(params[:id])
  end

  def destroy

    # find that chat user relation and destroy it
    current_user.chat_users.find_by(chat_id: params[:id]).destroy
    render nothing: true
  end

  # update menu
  def event_update 
    @user = current_user
    @users = get_current_users   
  end

  def get_current_users
    @users = []
    Chat.find_by(event_id: current_user.event_id, category: "main").users.each do |u|
      @users << u
    end
      return @users
  end
  
  private
  def chat_params
    params.permit(:event_id, :category)
  end

end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/event_update.html.erb
<ul id="navigation">
    <label id='menu-label'>CONVERSATIONS</label>
      <% @user.chats.order('created_at ASC').each do |c| %>
        <li class='menu-item convo-joined'>
          <% if c.category == 'main' %>
            <%= link_to "#{c.category}"+" - #{truncate(c.event.name, length: 23)}", '#', :data => {category: c.category, event_id: c.event_id}, class: 'start-chat hide-menu' %>
          <% else %>
            <%= link_to "#{truncate(c.category, length: 30)}", '#', :data => {category: c.category, event_id: c.event_id}, class: 'start-chat hide-menu' %>
          <% end %>
          <% if c.category != 'main' %>
            <%= link_to remove_chat_path(c), method: :delete, remote: true do %>
            <span class='close fa fa-times'></span>
            <% end %>
          <% end %>
        </li>
      <% end %>
    </div>


  <div class="autoscroll-menu">
    <%# if distance < 100.0 %>
      <div class='menu-section'>
        <label id='menu-label'>PEOPLE</label>
          <% @users.each do |u| %>
            <li class='menu-item'>
              <%= image_tag u.photo, class: 'menu-photo' %>
              <%= link_to u.name, user_path(u) %>
            </li>
          <% end %>
      </div>
    <%# end %>


    <div class='menu-section'>
        <label id='menu-label'>SETTINGS</label>
        <li class='left-padding'><%= link_to 'Edit Profile', edit_user_path(current_user) %></li>
        <li class='left-padding'><%= link_to 'Account Settings', edit_user_registration_path %></li>
        <!-- <li class='left-padding'><a target ="_blank" href='/#about-text'>About</a></li> -->
        <li class='left-padding'><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
    </div>
  </div>
  <a target="_blank" class="aboutlink" href="http://wildebee.st/">Created By wildebeest</a>
</ul>
  

app/views/chats/leavechat.html.erb
<%= disconnect chat_path(@chat) %>

app/views/chats/show.html.erb
<!-- hide this data and replace it in the header -->
<div class="chatboxcontent" id="chatboxcontent_<%=@chat.id%>">
  <% if @messages.any? %>
      <%= render @messages %>
  <% end %>
</div>


<div class="chatboxinput">
  <div id='chatbox-input-bg' class='expand'>

  <%= form_for([@chat, @message], :remote => true, :html => {id: "chat_form_#{@chat.id}"}) do |f| %>
      <div class="message-input-area">
        <%= f.text_area :body, :autofocus => true, class: "chatboxtextarea", "data-cid" => @chat.id, placeholder: "Share a message", id: "chat_input_#{@chat.id}" %>
        <div class="click-to-send-message" data-cid=<%=@chat.id%>>Send</div>
      </div>
  <% end %>
  </div>
</div>
 
<!-- check to see if user already subscribed without refreshing, set and save after -->
<% if current_user.chat_users.find_by(chat_id: @chat.id).subscribed == false%>
  <%= subscribe_to chat_path(@chat) %>
  <% x = current_user.chat_users.find_by(chat_id: @chat.id); x.subscribed = true; x.save%>
<%end%>  
  