config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks"}
  
  # For all non-Devise user pages
  resources :users
  resources :interests


  post '/users/:id/edit' => 'users#update_interest'

  post '/get_meetup_info' => 'pages#get_meetup_info'
  # Method for the user to select a location
  get '/select_location' => 'pages#select_location'
  # Saves user's interests using AJAX from the edit_user page
  post '/save_interest' => 'interests#save_interest'
  # Click on the X in the menu to remove a chat
  delete '/remove_chat/:id' => 'chats#destroy', as: 'remove_chat'

  resources :chats do
    resources :messages
  end

  # Direct the user to the chat room
  get '/events/:id' => 'events#show'
  resources :events
  # Clicking on main menu icon refreshes the menu contents
  get '/event_update' => 'chats#event_update'
  # Enought chatting for one day
  post '/unsubscribe/:id' => 'chats#leavechat'

end

app/views/layouts/_header.html.erb
<header>
	<% if params[:controller] == 'users' && params[:action] == 'show' %>
		<%= link_to "Back", event_path(@user.event_id), class: 'back' %>
		
		<% if @user.phone != '' && @user.private_messages %>
		<a href="sms:<%=@user.phone.gsub(/[^0-9]/, '') %>"><span class='fa fa-envelope' id='mail'>&nbsp;SMS</span></a>
		<% end %>
		<!-- <p class='current-room'><%#= truncate(@user.event_name, length: 30) %></p> -->
	<% else %>
		<span class="main-menu fa fa-list-ul"></span>
		
		<% if params[:controller] == 'events' %>
			<div class='page-title'><%= @chat.category %> - <%= truncate(@chat.event.name, length: 16)%>(<%=@chat.users.count%>)</div>
		<%else %>
		<%end %>
	<% end %>
</header>

app/views/layouts/_menu.html.erb
<!-- This partial only renders on the events controller per application.js -->

<!-- Container at the top for the logged in user -->
<div id='menu-user-info'>
	<%= image_tag current_user.photo, class: 'menu-main-photo' %><%= link_to current_user.name, user_path(@user), id:'logged-in-user-name' %>
</div>

<ul id="navigation">
	<label id='menu-label'>CONVERSATIONS</label>

	<!-- Display all of the user's chatrooms -->
	<% @user.chats.order('created_at ASC').each do |c| %>
		<li class='menu-item convo-joined'>

			<!-- If the chatroom name is 'main', display the meetup event name and don't let the user delete it -->
			<% if c.category == 'main' %>
				<%= link_to "#{c.category}"+" - #{truncate(c.event.name, length: 23)}", '#', :data => {category: c.category, event_id: c.event_id}, class: 'start-chat hide-menu' %>
			<% else %>

			<!-- If the chatroom name is not main, allow the user to delete it from their menu -->
				<%= link_to "#{truncate(c.category, length: 30)}", '#', :data => {category: c.category, event_id: c.event_id}, class: 'start-chat hide-menu' %>
				<%= link_to remove_chat_path(c), method: :delete, remote: true do %>
				<span class='close fa fa-times'></span>
				<% end %>
			<% end %>
		</li>
	<% end %>

	<div class="autoscroll-menu">
		<!-- If the user is less than x miles from the event venue, then let them see the attendees/profiles -->
		<!-- inital load prevents user list from showing if user is too far here -->
		<% if @distance < 10.25 %>
			<div class='menu-section'>
				<label id='menu-label'>PEOPLE</label>
				<% get_current_users.each do |u| %>
					<li class='menu-item'>
						<%= image_tag u.photo, class: 'menu-photo' %>
						<%= link_to u.name, user_path(u) %>
					</li>
				<% end %>
			</div>
		<% end %>

		<div class='menu-section'>
			<label id='menu-label'>SETTINGS</label>
			<li class='left-padding'><%= link_to 'Edit Profile', edit_user_path(current_user) %></li>
			<li class='left-padding'><%= link_to 'Account Settings', edit_user_registration_path %></li>
			<!-- <li class='left-padding'><a target="_blank" href='/#about-text'>About</a></li> -->
			<li class='left-padding'><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
		</div>
	</div>
  	<a target="_blank" class="aboutlink" href="http://wildebee.st/">Created By wildebeest</a>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>MetaMeetup - Meet the right people</title>
        
        <link rel="shortcut icon" href="/favicon.ico?v=2" />
        <%= favicon_link_tag 'apple-touch-icon-114x114.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '114x114' %>
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link href='https://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
        <meta name="viewport" content="width=device-width, initial-scale=1, content=minimal-ui">

        <!-- Display pretty on mobile browsers -->
        <meta name="mobile-web-app-capable" content="yes">

        <!-- Make it look more like an app on iphones -->
        <meta name="apple-mobile-web-app-status-bar-style" content="black">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">

        <!-- To allow Google Chrome users to save shortcut to desktop -->
        <link rel="manifest" href="manifest.json">

        <!-- sets meta data for view used for chats-->
        <meta content='<%= user_signed_in? ? current_user.id : "" %>' name='user-id'/>
    </head>

    <!-- disable turbolinks and if the user is on the sessions controller, give body the class 'homepage' -->
    <body data-no-turbolink id='body' class=<%= params[:controller] == 'devise/sessions' ? 'homepage' : ''%>>
        <% if flash[:alert] %>
  		    <p id="alert"><%= alert %></p>
  		<% end %>
  		<% if flash[:notice] %>
  		    <p class="notice"><%= notice %></p>
  		<% end %>
        <% if params[:controller] == 'events' %>
            <div id="menu"><%= render 'layouts/menu' %></div>
            <div id="site"><%= render 'layouts/header' %>
        <% end %>

        <!-- Display a sign out link atop the page when the user is on the select_location screen -->
        <% if params[:action] == 'select_location' %>
            <p class='sign-out'>Signed in as <%= @user.email %> | <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></p>
        <% end %>

        <!-- Render the magic here -->
        <%= yield %>

            <!-- Disjointed closing div to wrap the site in an element to allow it to slide when the menu opens -->
            </div>

    <!-- Google Analytics -->
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-53470484-5', 'auto');
        ga('send', 'pageview');
    </script>
  </body>
  
</html>